"use client";

import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";

/* ------------------------------------------------------------------ */
/*  Types                                                               */
/* ------------------------------------------------------------------ */

interface DaySchedule {
  day: number;
  warmupEmails: number;
  coldEmails: number;
  totalEmails: number;
  warmupPct: number;
}

/* ------------------------------------------------------------------ */
/*  Schedule generation logic                                           */
/* ------------------------------------------------------------------ */

function generateSchedule(
  mailboxes: number,
  targetVolume: number,
  startDay: number
): DaySchedule[] {
  const schedule: DaySchedule[] = [];

  for (let d = startDay; d < startDay + 30; d++) {
    const dayIndex = d; // absolute warmup day
    // Volume ramp: starts at ~2/day, exponentially ramps to target over ~25 days
    const rampFactor = Math.min(1, dayIndex / 25);
    const dailyVolume = Math.max(
      2,
      Math.round(2 + (targetVolume - 2) * Math.pow(rampFactor, 1.5))
    );
    const totalEmails = dailyVolume * mailboxes;

    // Warmup ratio: starts at 100% warmup, gradually shifts
    // Day 0-5: 100% warmup, Day 6-15: shifts to 50/50, Day 16+: 20% warmup
    let warmupPct: number;
    if (dayIndex <= 5) {
      warmupPct = 100;
    } else if (dayIndex <= 15) {
      warmupPct = Math.round(100 - ((dayIndex - 5) / 10) * 50);
    } else if (dayIndex <= 25) {
      warmupPct = Math.round(50 - ((dayIndex - 15) / 10) * 30);
    } else {
      warmupPct = 20;
    }

    const warmupEmails = Math.round((totalEmails * warmupPct) / 100);
    const coldEmails = totalEmails - warmupEmails;

    schedule.push({
      day: d,
      warmupEmails,
      coldEmails,
      totalEmails,
      warmupPct,
    });
  }

  return schedule;
}

function scheduleToText(
  schedule: DaySchedule[],
  mailboxes: number,
  targetVolume: number
): string {
  let text = `Email Warmup Schedule\n`;
  text += `Generated by ColdRelay (https://coldrelay.com/tools/warmup-schedule-generator)\n`;
  text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  text += `Mailboxes: ${mailboxes} | Target Volume: ${targetVolume}/mailbox/day\n\n`;
  text += `${"Day".padEnd(6)}${"Total".padEnd(10)}${"Warmup".padEnd(10)}${"Cold".padEnd(10)}${"Warmup %".padEnd(10)}\n`;
  text += `${"─".repeat(46)}\n`;

  for (const day of schedule) {
    text += `${String(day.day).padEnd(6)}`;
    text += `${String(day.totalEmails).padEnd(10)}`;
    text += `${String(day.warmupEmails).padEnd(10)}`;
    text += `${String(day.coldEmails).padEnd(10)}`;
    text += `${String(day.warmupPct + "%").padEnd(10)}\n`;
  }

  text += `\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  text += `Tip: ColdRelay handles warmup automatically — https://coldrelay.com\n`;
  return text;
}

/* ------------------------------------------------------------------ */
/*  FAQ                                                                 */
/* ------------------------------------------------------------------ */

const faqs = [
  {
    q: "What is email warmup?",
    a: "Email warmup is the process of gradually increasing the sending volume from a new mailbox to build a positive sender reputation with email providers like Gmail, Outlook, and Yahoo. It involves sending emails that get opened, replied to, and marked as important — signaling to ISPs that you're a legitimate sender.",
  },
  {
    q: "How long does email warmup take?",
    a: "A typical warmup period is 14-30 days, depending on your target daily volume. Higher volumes require longer warmup periods. Starting to send cold emails too early — before your mailbox has established reputation — can damage deliverability and get you flagged as spam.",
  },
  {
    q: "What's the difference between warmup emails and cold emails?",
    a: "Warmup emails are sent to a network of real inboxes that automatically open, reply, and interact with your messages to build reputation. Cold emails are your actual outreach to prospects. During warmup, you gradually shift the ratio from mostly warmup to mostly cold emails.",
  },
  {
    q: "How many mailboxes do I need for cold email?",
    a: "A common guideline is to keep each mailbox under 30-50 emails per day to maintain deliverability. For 500 cold emails/day, you'd need 10-17 mailboxes. Use our Mailbox Sizing Calculator for a precise recommendation based on your volume goals.",
  },
  {
    q: "Can I skip the warmup period?",
    a: "Skipping warmup is one of the most common reasons cold email campaigns fail. New mailboxes have zero reputation — sending even 20 cold emails from a fresh mailbox can trigger spam filters. The warmup period is essential for sustainable cold outreach.",
  },
];

/* ------------------------------------------------------------------ */
/*  Component                                                           */
/* ------------------------------------------------------------------ */

export default function WarmupScheduleGeneratorPage() {
  const [mailboxes, setMailboxes] = useState("5");
  const [targetVolume, setTargetVolume] = useState("30");
  const [startDay, setStartDay] = useState("0");
  const [schedule, setSchedule] = useState<DaySchedule[] | null>(null);
  const [faqOpen, setFaqOpen] = useState<number | null>(null);

  const handleGenerate = () => {
    const m = Math.max(1, parseInt(mailboxes) || 1);
    const t = Math.max(5, parseInt(targetVolume) || 30);
    const s = Math.max(0, parseInt(startDay) || 0);
    setSchedule(generateSchedule(m, t, s));
  };

  const handleDownload = () => {
    if (!schedule) return;
    const m = parseInt(mailboxes) || 5;
    const t = parseInt(targetVolume) || 30;
    const text = scheduleToText(schedule, m, t);
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "warmup-schedule.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const totalWarmup = schedule?.reduce((s, d) => s + d.warmupEmails, 0) ?? 0;
  const totalCold = schedule?.reduce((s, d) => s + d.coldEmails, 0) ?? 0;
  const peakVolume = schedule ? Math.max(...schedule.map((d) => d.totalEmails)) : 0;

  return (
    <>
      {/* Schema */}
      <script
        type="application/ld+json"
        suppressHydrationWarning
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebApplication",
            name: "Email Warmup Schedule Generator",
            url: "https://coldrelay.com/tools/warmup-schedule-generator",
            applicationCategory: "BusinessApplication",
            operatingSystem: "Any",
            offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
          }),
        }}
      />
      <script
        type="application/ld+json"
        suppressHydrationWarning
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: faqs.map((f) => ({
              "@type": "Question",
              name: f.q,
              acceptedAnswer: { "@type": "Answer", text: f.a },
            })),
          }),
        }}
      />

      {/* Hero */}
      <section className="pt-16 sm:pt-24 pb-12 sm:pb-16 relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-[#4A73D5]/[0.06] rounded-full blur-[120px]" />
        </div>
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <Link
            href="/tools"
            className="inline-flex items-center gap-1 text-xs text-white/40 hover:text-white/60 transition-colors mb-6"
          >
            ← All Tools
          </Link>
          <div className="inline-flex items-center gap-2 rounded-full border border-[#4A73D5]/20 bg-[#4A73D5]/10 px-3 py-1 mb-6 ml-3">
            <span className="text-xs font-medium tracking-wide uppercase text-[#6B8FE6]">
              Free Tool
            </span>
          </div>
          <h1 className="text-3xl sm:text-4xl md:text-5xl text-white tracking-tight leading-tight font-bold mb-5">
            Email Warmup Schedule Generator
          </h1>
          <p className="text-base sm:text-lg text-white/60 leading-relaxed max-w-xl mx-auto">
            Generate a 30-day warmup calendar for your cold email mailboxes. See the day-by-day
            volume ramp and warmup vs cold email split.
          </p>
        </div>
      </section>

      {/* Generator */}
      <section className="pb-16 sm:pb-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="rounded-2xl border border-white/[0.08] bg-white/[0.02] backdrop-blur-sm p-6 sm:p-8"
          >
            <div className="grid sm:grid-cols-3 gap-4 mb-6">
              <div>
                <label className="block text-sm font-medium text-white/70 mb-2">
                  Number of Mailboxes
                </label>
                <input
                  type="number"
                  min="1"
                  max="100"
                  value={mailboxes}
                  onChange={(e) => setMailboxes(e.target.value)}
                  className="w-full rounded-xl bg-white/[0.06] border border-white/[0.1] px-4 py-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:ring-2 focus:ring-[#4A73D5]/40 focus:border-[#4A73D5]/40 transition-all"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-white/70 mb-2">
                  Target Volume / Mailbox / Day
                </label>
                <input
                  type="number"
                  min="5"
                  max="100"
                  value={targetVolume}
                  onChange={(e) => setTargetVolume(e.target.value)}
                  className="w-full rounded-xl bg-white/[0.06] border border-white/[0.1] px-4 py-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:ring-2 focus:ring-[#4A73D5]/40 focus:border-[#4A73D5]/40 transition-all"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-white/70 mb-2">
                  Current Warmup Day (0 = fresh)
                </label>
                <input
                  type="number"
                  min="0"
                  max="30"
                  value={startDay}
                  onChange={(e) => setStartDay(e.target.value)}
                  className="w-full rounded-xl bg-white/[0.06] border border-white/[0.1] px-4 py-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:ring-2 focus:ring-[#4A73D5]/40 focus:border-[#4A73D5]/40 transition-all"
                />
              </div>
            </div>
            <button
              onClick={handleGenerate}
              className="w-full sm:w-auto rounded-xl bg-[#4A73D5] hover:bg-[#5A83E5] px-8 py-3 text-sm font-semibold text-white shadow-lg shadow-[#4A73D5]/20 hover:shadow-[#4A73D5]/30 transition-all"
            >
              Generate Schedule
            </button>
          </motion.div>

          {/* Results */}
          <AnimatePresence>
            {schedule && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.4 }}
                className="mt-8"
              >
                {/* Summary cards */}
                <div className="grid grid-cols-3 gap-4 mb-6">
                  <div className="rounded-xl border border-[#4A73D5]/20 bg-[#4A73D5]/[0.06] p-4 text-center">
                    <p className="text-xs text-white/40 mb-1">Peak Daily Volume</p>
                    <p className="text-lg font-bold text-[#6B8FE6]">
                      {peakVolume.toLocaleString()}
                    </p>
                  </div>
                  <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/[0.06] p-4 text-center">
                    <p className="text-xs text-white/40 mb-1">30-Day Warmup Emails</p>
                    <p className="text-lg font-bold text-emerald-400">
                      {totalWarmup.toLocaleString()}
                    </p>
                  </div>
                  <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4 text-center">
                    <p className="text-xs text-white/40 mb-1">30-Day Cold Emails</p>
                    <p className="text-lg font-bold text-white">
                      {totalCold.toLocaleString()}
                    </p>
                  </div>
                </div>

                {/* Download button */}
                <div className="flex justify-end mb-4">
                  <button
                    onClick={handleDownload}
                    className="inline-flex items-center gap-2 rounded-lg bg-white/[0.06] border border-white/[0.1] px-4 py-2 text-xs font-medium text-white/70 hover:text-white hover:bg-white/[0.1] transition-all"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download as Text
                  </button>
                </div>

                {/* Schedule table */}
                <div className="rounded-2xl border border-white/[0.08] bg-white/[0.02] overflow-hidden">
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-white/[0.06]">
                          <th className="text-left px-4 py-3 text-xs font-medium text-white/40 uppercase tracking-wider">Day</th>
                          <th className="text-right px-4 py-3 text-xs font-medium text-white/40 uppercase tracking-wider">Total</th>
                          <th className="text-right px-4 py-3 text-xs font-medium text-white/40 uppercase tracking-wider">Warmup</th>
                          <th className="text-right px-4 py-3 text-xs font-medium text-white/40 uppercase tracking-wider">Cold</th>
                          <th className="text-right px-4 py-3 text-xs font-medium text-white/40 uppercase tracking-wider">Warmup %</th>
                          <th className="px-4 py-3 text-xs font-medium text-white/40 uppercase tracking-wider">Split</th>
                        </tr>
                      </thead>
                      <tbody>
                        {schedule.map((day, i) => (
                          <motion.tr
                            key={day.day}
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            transition={{ delay: i * 0.02 }}
                            className="border-b border-white/[0.04] last:border-0 hover:bg-white/[0.02]"
                          >
                            <td className="px-4 py-3 font-medium text-white">Day {day.day}</td>
                            <td className="px-4 py-3 text-right text-white/70">{day.totalEmails}</td>
                            <td className="px-4 py-3 text-right text-emerald-400">{day.warmupEmails}</td>
                            <td className="px-4 py-3 text-right text-[#6B8FE6]">{day.coldEmails}</td>
                            <td className="px-4 py-3 text-right text-white/50">{day.warmupPct}%</td>
                            <td className="px-4 py-3">
                              <div className="flex h-2 rounded-full overflow-hidden bg-white/[0.06] w-24">
                                <div
                                  className="bg-emerald-500/60 transition-all"
                                  style={{ width: `${day.warmupPct}%` }}
                                />
                                <div
                                  className="bg-[#4A73D5]/60 transition-all"
                                  style={{ width: `${100 - day.warmupPct}%` }}
                                />
                              </div>
                            </td>
                          </motion.tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-16 sm:py-24 border-t border-white/[0.06]">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl sm:text-3xl font-bold text-white text-center mb-10">
            Frequently Asked Questions
          </h2>
          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <div
                key={i}
                className="rounded-xl border border-white/[0.06] bg-white/[0.02] overflow-hidden"
              >
                <button
                  className="w-full text-left px-5 py-4 flex items-center justify-between gap-3"
                  onClick={() => setFaqOpen(faqOpen === i ? null : i)}
                >
                  <span className="text-sm font-medium text-white">{faq.q}</span>
                  <svg
                    className={`w-4 h-4 text-white/30 flex-shrink-0 transition-transform ${faqOpen === i ? "rotate-180" : ""}`}
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                  </svg>
                </button>
                {faqOpen === i && (
                  <div className="px-5 pb-4">
                    <p className="text-sm text-white/50 leading-relaxed">{faq.a}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 sm:py-20 border-t border-white/[0.06]">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="rounded-2xl border border-[#4A73D5]/20 bg-[#4A73D5]/[0.04] p-8 sm:p-10 text-center">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight mb-4">
              ColdRelay Handles Warmup Automatically
            </h2>
            <p className="text-base text-white/50 mb-8 max-w-xl mx-auto">
              Stop managing warmup schedules manually. ColdRelay automatically warms up every
              mailbox with real interactions — opens, replies, and rescues from spam. Your
              deliverability stays high without any effort.
            </p>
            <a
              href="https://app.coldrelay.com/auth/register"
              className="inline-flex items-center gap-2 rounded-full bg-[#4A73D5] hover:bg-[#5A83E5] px-8 py-4 text-sm font-semibold text-white shadow-lg shadow-[#4A73D5]/20 hover:shadow-[#4A73D5]/30 hover:brightness-110 transition-all uppercase tracking-wide"
            >
              Get Started Free →
            </a>
          </div>
        </div>
      </section>
    </>
  );
}
